// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FaveImagesController from "./fave_images_controller"
application.register("fave-images", FaveImagesController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PopUpMsgController from "./pop_up_msg_controller"
application.register("pop-up-msg", PopUpMsgController)

import Reminders2Controller from "./reminders2_controller"
application.register("reminders2", Reminders2Controller)

import RemindersController from "./reminders_controller"
application.register("reminders", RemindersController)
